
import pathlib

BASEDIR = pathlib.Path(__file__).parent.parent.resolve()


NUM_SELF_PLAY_GAMES = 100
SEED = None
BOARD_SIZE = 9
KOMI = 6.0
ALLOW_SUICIDE = False
KO = "simple"
EARLY_END_PASS_ALIVE = True
END_ON_TWO_PASSES = True
MCTS_SIMS = 800
C_PUCT = 1.4
DIRICHLET_ALPHA = 0.15
DIRICHLET_EPS = 0.25
TEMPERATURE_MOVES = 10
PARALLEL_SELF_PLAY = True
NUM_WORKERS = 12
OUTPUT_DIR = BASEDIR/"data/self_play_data"
IN_CHANNELS = 2